### ISSUE TITLE
Guess what? new name.........

### ISSUE THREAD

**Issue by hrdwrrsk** [hrdwrrsk/adementary-theme#29]
Originally, this theme are called (Project) Beaucoup, then renamed to Tetra. however, I think I should rename this project (again), some possible candidates:

- Elemental
- Admentary / Adwentary
- Elementaire
- Adwaitheon

or suggest any other name

**Comment by geek1011** [comment]
I personally like Elemental the best out of those options.

**Comment by hrdwrrsk** [comment]
Update | another name candidates:
- **Ermine** (named after Ubuntu 19.10 [https://www.omgubuntu.co.uk/2019/04/ubuntu-19-10-codename](codename reveal)) but it seems 50/50 chance
- **Sacramento**
- **Adwaitary** (90% chance along with Adwaitheon or Adwentary)
