### ISSUE TITLE
Dark headerbar variant

### ISSUE THREAD

**Issue by clumsyfingers** [hrdwrrsk/adementary-theme#32]
any chance of a darker version. i mean darker as in dark headerbar and light body

**Comment by hrdwrrsk** [comment]
It originally planned. I already experimented with them but I quickly discarded it for some reason


but at one day, I will experiment again with dark headerbar variant, currently it's low priority

**Comment by hrdwrrsk** [comment]
If anyone interested to make "darker"/dark headerbar variant, you can make PRs in this repo and leave discussion there.

**Comment by SaucySauce** [comment]
I'm making a "darker" fork. https://github.com/SaucySauce/adementary-darker-theme
