### ISSUE TITLE
XFCE - Buttons on task bar are difficult to press

### ISSUE THREAD

**Issue by digiberk** [hrdwrrsk/adementary-theme#33]
Hello again,

So I'm trying out XFCE and I'm surprised to find that this theme works beautifully with this desktop environment. Everything looks super polished, keep up the great work!

One minor problem I've come across (albeit an annoying one), is that it is difficult to click the window buttons / task bar buttons when I bring the mouse all the way down. Here is a screenshot of what I mean.

![DIFFICULT TO PRESS XFCE](https://user-images.githubusercontent.com/38805550/59141920-a4208480-89f8-11e9-8f0b-7d705a655c08.png)

When the cursor is over the "[berk - File Manager]" I can click on the button normally. The problem however is that I can't click on the button if the **cursor** is below the button. This means, when I naturally bring the cursor to click on another window, it is difficult to press the desired window because of the padding around the button and taskbar itself. Is there a way to resolve this? 

It would be nice to leave the borders around the taskbar buttons as is because they look great. If you want to test out the desired behaviour of buttons in XFCE, Adwaita behaves normally due to the large buttons.

**Comment by hrdwrrsk** [comment]
mmm.... seems I should remove extra padding/margin that I implemented it before (actually it's to achieve WinXP/Vista-style thing or some classic Gtk2 themes like clearlooks)

**Comment by digiberk** [comment]
Sounds good. I just pulled down the theme again and now it is more usable. The Clearlooks/WinXP style did look better because now it is very flat but I guess it behaves like Greybird now. I'm mainly on GNOME these days so no problems for me there, it looks splendid!

Just one more thing, when you uncheck "Show flat buttons" in the window buttons properties, the buttons go all white. Not a problem for me as I have it enabled but if someone was to install this theme and they don't know this toggle, they may have issues.
