### ISSUE TITLE
CSD aren't constant between apps

### ISSUE THREAD

**Issue by SaucySauce** [hrdwrrsk/adementary-theme#39]
![Screenshot from 2019-06-17 23:20:37](https://user-images.githubusercontent.com/38703177/59643011-b7e58c80-9156-11e9-80f8-8b344d25fc88.png)

The Image viewer app and Gedit don't have the same CSD measurements. The buttons aren't size set to the same standard. Same occurs in Dconf-editor.

**Comment by hrdwrrsk** [comment]
this actually attempt to make the CSD/header bars compact a long time ago, originally this theme use large (but not larger like Adwaita) size widgets

and yes, this theme actually designed for small font size (9pt recommended)

I'm sure other Adwaita forks like Minwaita will have this 'growing' header bar size if using large fonts

**Comment by SaucySauce** [comment]
That means I just need to use a smaller font?

**Comment by hrdwrrsk** [comment]
yes, 10pt size font size also not affected with this problem


but it seems you're using a FHD display (1080p) 13-inch laptop

**Comment by SaucySauce** [comment]
720p 13.3 MacBook Pro from 2011.
Ok, I'll use 10.

**Comment by SaucySauce** [comment]
Budgie Desktop Settings (BDS) has a big oopsie.

![Screenshot from 2019-06-17 23:47:37](https://user-images.githubusercontent.com/38703177/59643959-5de6c600-915a-11e9-825e-d7766c7a0fb6.png)

From Left to Right, Image viewer, GNOME settings, Gedit, Lollypop, Budgie Desktop Settings.
Odd considering BDS has no need for CSD as of right now.

**Comment by SaucySauce** [comment]
Same with size 10 font.
