### ISSUE TITLE
Making a Darker fork

### ISSUE THREAD

**Issue by SaucySauce** [hrdwrrsk/adementary-theme#41]
https://github.com/SaucySauce/adementary-darker-theme

Still plenty to do, especially buttons and comboboxes. Server side decorations still need to be done.

**Comment by hrdwrrsk** [comment]
why creating new fork than making a new pull request? so it can merged to upstream (this repo)

**Comment by SaucySauce** [comment]
I know nothing about how GitHub works. This is all still very new to me.

**Comment by hrdwrrsk** [comment]
umm ok

**Comment by SaucySauce** [comment]
It's only one file that I'm changing. 3.24 gtk.css.
