### ISSUE TITLE
Budgie panel, Black indicator in active app

### ISSUE THREAD

**Issue by SaucySauce** [hrdwrrsk/adementary-theme#42]
![Screenshot from 2019-06-18 16:42:44](https://user-images.githubusercontent.com/38703177/59702893-4bb36900-91e8-11e9-8fd7-627b40eb77ee.png)

The focused, active window indicator is black.
A hovered open application but not focused is blue.
Budgie 10.5. Ubuntu 19.04.

**Comment by hrdwrrsk** [comment]
it's designed for light panel to make it contrast-y than using blue accent color, it's also same on Cinnamon's new grouped window list applet, or dash-to-dock/panel GNOME shell extension

**Comment by SaucySauce** [comment]
Ok.
