### ISSUE TITLE
Pamac package manager headerbar bug

### ISSUE THREAD

**Issue by SaucySauce** [hrdwrrsk/adementary-theme#54]
![Screenshot-20200102023917-959x645](https://user-images.githubusercontent.com/38703177/71650924-1d6f2400-2d09-11ea-8f73-b15876751476.png)
![Screenshot-20200102023908-959x645](https://user-images.githubusercontent.com/38703177/71650925-1d6f2400-2d09-11ea-89b2-847cbe614bf2.png)

If you look closely something happens when the category list button is showing that makes the headerbar increase height. This doesn't happen on Adwaita.

**Comment by hrdwrrsk** [comment]
this is headerbar height issue since this theme uses smaller headerbar height

also, please test it with other GTK themes with small(er) headerbar height, like "compact Adwaita" forks or tista500's plata-theme (compact version)

**Comment by SaucySauce** [comment]
So far tested ant-dracula-gtk-theme 1.3.0-1 on AUR doesn't have the bug.

**Comment by SaucySauce** [comment]
arc-gtk-theme is also ok.

**Comment by SaucySauce** [comment]
plata-theme is taking too long to compile.

**Comment by SaucySauce** [comment]
Minwaita has this bug though.

**Comment by SaucySauce** [comment]
Materia-compact is fine.

**Comment by hrdwrrsk** [comment]
also affects in some apps that uses libhandy's headerbar stackswitcher (like GNOME News, Authenticator (setting dialog only))

so I will increase headerbar height than messing up anything

**Comment by hrdwrrsk** [comment]
so I made the headerbar became t h i c c at all, hope you like it

![Screenshot from 2020-01-09 19-52-14](https://user-images.githubusercontent.com/9630564/72069394-a85baa00-3319-11ea-823c-4e9a962bbd20.png)

**Comment by SaucySauce** [comment]
Not gonna lie, looked much better before. Also, Pamac still suffers from the same bug. I don't know, I can live with the bug in Pamac and Dconf(not bugged in the current thicc update).

**Comment by SaucySauce** [comment]
Correction, it's growing on me a bit but before is still better I think.

**Comment by SaucySauce** [comment]
Although I'm on a 1280 by 800 13' monitor. So what do I know...

**Comment by hrdwrrsk** [comment]
can confirm, seems more like pamac uses hardcoded headerbar (styling?), I will figure it out with GtkInspector and etc.

**Comment by SaucySauce** [comment]
Will you go back to s l i m headerbars? The more I see nautilus the more it freaks me out, like a big fat face with tiny center lined eyes. Btw, off topic, is there any way of forcing indicators in the status area to have the same trigger area?

**Comment by hrdwrrsk** [comment]
> Will you go back to s l i m headerbars? The more I see nautilus the more it freaks me out, like a big fat face with tiny center lined eyes. Btw, off topic, is there any way of forcing indicators in the status area to have the same trigger area?

maybe not, since GTK apps that uses libhandy stackswitcher has large height and seems kinda 'hardcoded' for me :\

**Comment by SaucySauce** [comment]
Could you at least add a variation in the install script to allow using either slim or T H I C C? like ./install.sh -d -c (or -t for thicc) ~/.themes. Pretty please?

**Comment by hrdwrrsk** [comment]
> Could you at least add a variation in the install script to allow using either slim or T H I C C? like ./install.sh -d -c (or -t for thicc) ~/.themes. Pretty please?

Noted for future, please note that this theme are in "slow development" mode since I was actively working in new AdwaitaExtended theme, check it out :)

**Comment by SaucySauce** [comment]
Oh thanks, I shall check it out. FYI, I reinstalled a backup of the last slim Adementary update.

**Comment by SaucySauce** [comment]
Also, I'll try to make this theme more well known. I think I've said it before.

**Comment by hrdwrrsk** [comment]
> > Will you go back to s l i m headerbars? The more I see nautilus the more it freaks me out, like a big fat face with tiny center lined eyes. Btw, off topic, is there any way of forcing indicators in the status area to have the same trigger area?
> 
> maybe not, since GTK apps that uses libhandy stackswitcher has large height and seems kinda 'hardcoded' for me :\

Ah, actually it's possible to use small height in libhandy (headerbar) stackswitcher button:
`
headerbar hdyviewswitcher > button > stack > box {
	padding: 0;
}
`

**Comment by SaucySauce** [comment]
Well, the only I'm not helping out with the code is because I'm clueless about GTK.

**Comment by SaucySauce** [comment]
Just tried it again and Pamac no longer shows the bug.
