### ISSUE TITLE
Developing a No Title Bar extension buttons theme for this theme

### ISSUE THREAD

**Issue by SaucySauce** [hrdwrrsk/adementary-theme#55]
Right now I'm (https://github.com/SaucySauce/adementary-no-title-bar-extension-buttons) just taking bits and pieces of your work into a theme for No Title Bar extension (https://github.com/poehlerj/no-title-bar) set of themes. Just giving you a heads up. Right now it only lacks the checkbox icons (hover and pressed) around the control buttons.

**Comment by hrdwrrsk** [comment]
might check it out but i don't use no title bar extension, maybe interesting to add more GS extension theming support and currently this project almost unmaintained a bit

**Comment by SaucySauce** [comment]
Don't give up, I'll try to make this theme better known to the community, you're doing a great job. I'm a big fan of Pantheon but it's too restricted, you and a few extension developers are doing an amazing work at making GNOME Shell great again.
![Screenshot-20200107141341-1280x800](https://user-images.githubusercontent.com/38703177/71905673-253f2600-3158-11ea-8629-36ac13f4bd49.png)
