### ISSUE TITLE
Adding border exception to Dash2Dock edge 

### ISSUE THREAD

**Issue by SaucySauce** [hrdwrrsk/adementary-theme#56]
Any way to remove this border when the panel is extended edge to edge? I removed the background to make it easier to see.
![Screenshot-20200108213253-1280x800](https://user-images.githubusercontent.com/38703177/72021851-95d06a80-325e-11ea-9709-1f46e672cd5d.png)

**Comment by hrdwrrsk** [comment]
it's not border, it's highlight effect.

**Comment by SaucySauce** [comment]
![Screenshot-20200109085654-1280x800](https://user-images.githubusercontent.com/38703177/72057527-11adcf80-32be-11ea-8fff-709c93c0f712.png)
Using base Adementary theme with DtD custom dash color $dark_bg_color: #2E3038 as according to your color sass file.

**Comment by SaucySauce** [comment]
Thank you.
